export enum LoanStepEnum {
    CUSTOMER_SELECT = "CUSTOMER_SELECT",
    DETAIL = "DETAIL",
    ADDITIONAL = "ADDITIONAL",
    GUARANTOR_LIST = "GUARANTOR_LIST",
    CALCULATE = "CALCULATE",
    SUMMARY = "SUMMARY",
}
